//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Event_ManagementEntities : DbContext
    {
        public Event_ManagementEntities()
            : base("name=Event_ManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activite> Activites { get; set; }
        public virtual DbSet<ActivityTPYE> ActivityTPYES { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<Attende> Attendes { get; set; }
        public virtual DbSet<AttendesEvent> AttendesEvents { get; set; }
        public virtual DbSet<BookMark> BookMarks { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<FloorMapping> FloorMappings { get; set; }
        public virtual DbSet<FloorRegionMapping> FloorRegionMappings { get; set; }
        public virtual DbSet<ForumSocialComment> ForumSocialComments { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<PostType> PostTypes { get; set; }
        public virtual DbSet<PostUserLike> PostUserLikes { get; set; }
        public virtual DbSet<QRCode> QRCodes { get; set; }
        public virtual DbSet<QRHistory> QRHistories { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<SocialForum> SocialForums { get; set; }
        public virtual DbSet<Sponsor> Sponsors { get; set; }
        public virtual DbSet<SponsorsEvent> SponsorsEvents { get; set; }
        public virtual DbSet<Theme> Themes { get; set; }
        public virtual DbSet<UserEvent_Permission> UserEvent_Permission { get; set; }
    }
}
