//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FloorRegionMapping
    {
        public int ID { get; set; }
        public int EventID { get; set; }
        public int FMid { get; set; }
        public string Description { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> height { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual FloorMapping FloorMapping { get; set; }
    }
}
