//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theme
    {
        public int ID { get; set; }
        public int EventID { get; set; }
        public string SplashScreemURL { get; set; }
        public string AppBackgroundURL { get; set; }
        public string ButtonURL { get; set; }
        public string ButtonBackgroundColor { get; set; }
        public string ButtonForegroundColor { get; set; }
        public string LabelForegroundColor { get; set; }
        public string HeadingForegroundColor { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
